
DROP TABLE IF EXISTS review_likes;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS rating;


CREATE TABLE IF NOT EXISTS rating (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar,
    releaseDate timestamp,
    duration integer,
    rating_id INTEGER REFERENCES rating (rating_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id INTEGER REFERENCES film (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(35),
    login varchar(25),
    name varchar(25),
    birthday timestamp
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES film (film_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS review (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content varchar(200),
    positive boolean NOT NULL,
    user_id INTEGER REFERENCES users (user_id),
    film_id INTEGER REFERENCES film (film_id),
    useful INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id INTEGER REFERENCES users (user_id),
    user_id INTEGER REFERENCES users (user_id),
    is_like boolean NOT NULL,
    PRIMARY KEY(review_id, user_id)
);